qqqq/Controllers/BK_SubCategoryController.cs
using Microsoft.AspNetCore.Mvc;
using qqqq.ViewModels;
using qqqq.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace qqqq.Controllers
{
    public class BK_SubCategoryController : Controller
    {
        public IActionResult sbpetList()
        {

            我救浪Context db = new 我救浪Context();
            var datas = from S in db.SubCategories
                        where S.Category.IsPet == true && S.Category.CategoryName != "不限"
                        select S;
            List<CSubCategoryPet> list = new List<CSubCategoryPet>();
            foreach (SubCategory S in datas)
            {
                CSubCategoryPet sub = new CSubCategoryPet();
                sub.SubCategory = S;
                list.Add(sub);
            }
            return View(list);
        }


        //新增類別
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(SubCategory sub)
        {
            我救浪Context db = new 我救浪Context();

            db.SubCategories.Add(sub);
            db.SaveChanges();
            return RedirectToAction("sbpetList");
        }

        //刪除類別
        public IActionResult Delete(int? id)
        {
            我救浪Context db = new 我救浪Context();
            SubCategory sub = db.SubCategories.FirstOrDefault(S => S.SubCategoryId == id);
            if (sub != null)
            {
                db.SubCategories.Remove(sub);
                db.SaveChanges();
            }
            return RedirectToAction("sbpetList");
        }


        //修改類別
        public IActionResult Edit(int? id)
        {
            我救浪Context db = new 我救浪Context();
            SubCategory sub = db.SubCategories.FirstOrDefault(S => S.SubCategoryId == id);
            if (sub == null)
                return RedirectToAction("sbpetList");
            return View(new CSubCategoryPet(sub));
        }
        [HttpPost]
        public IActionResult Edit(SubCategory sub)
        {
            我救浪Context db = new 我救浪Context();
            SubCategory subCategory = db.SubCategories.FirstOrDefault(S => S.SubCategoryId == sub.SubCategoryId);
            if (subCategory != null)
            {
                subCategory.SubCategoryName = sub.SubCategoryName;
                db.SaveChanges();
            }
            return RedirectToAction("sbpetList");
        }

    }
}

qqqq/Views/BK_SubCategory/Create.cshtml
@model qqqq.ViewModels.CSubCategoryPet
@{
    ViewData["Title"] = "Create";
    Layout = "_BackLayout";

}
@section Styles{
    <style>
    #input{
        border:solid antiquewhite 2px;
        border-radius:20px;
        color:black;
        font-weight:400;
        background-color:antiquewhite;
    }
    label {
        color: black;
        font-weight: 900;
    }
    }
    </style>
    <h1 style="font-weight: 900; text-align:center; margin-top: 30px; margin-bottom: 10px">浪浪品種新增</h1>
    <div style="text-align:right; margin-right:10px; text-decoration:none">
        <a asp-action="sbpetList" class="fa-solid fa-right-from-bracket" style="color: chocolate;"> 返回</a>
    </div>
    <hr />
    <div class="row" style="padding-bottom:90px; display:flex;justify-content:center;align-items:center">
        <div class="col-md-4">
            <form asp-action="Create">
                <div id="input" asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group" hidden>
                    <label asp-for="SubCategoryId" class="control-label"></label>
                    <input asp-for="SubCategoryId" class="form-control" />
                    <span asp-validation-for="SubCategoryId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <i class="fa-solid fa-paw">
                        <label asp-for="CategoryName" class="control-label"></label>
                    </i>
                    <select id="input" asp-for="CategoryName" class="form-control">
                        <option></option>
                        <option>貓</option>
                        <option>狗</option>
                    </select>
                    <span asp-validation-for="CategoryName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <i class="fa-solid fa-paw">
                        <label asp-for="SubCategoryName" class="control-label"></label>
                    </i>
                    <input id="input" asp-for="SubCategoryName" class="form-control" />
                    <span asp-validation-for="SubCategoryName" class="text-danger"></span>
                </div>
                <div class="form-group" hidden>
                    <label asp-for="CategoryId" class="control-label"></label>
                    <input asp-for="CategoryId" class="form-control" />
                    <span asp-validation-for="CategoryId" class="text-danger"></span>
                </div>

                <div class="form-group" style="text-align:right">
                    <i class="fa-solid fa-floppy-disk">
                        <input id="input" type="submit" value="新增" />
                    </i>
                </div>
            </form>
        </div>
    </div>
    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

qqqq/Views/BK_SubCategory/Edit.cshtml
@model qqqq.ViewModels.CSubCategoryPet

@{
    ViewData["Title"] = "Edit";
    Layout = "_BackLayout";

}
@section Styles{
    <style>
    #input{
        border:solid antiquewhite 2px;
        border-radius:20px;
        color:black;
        font-weight:400;
        background-color:antiquewhite;
    }
    label {
        color: black;
        font-weight: 900;
    }
    }
    </style>
    <div>
        <h1 style="font-weight:900; text-align:center; margin-top: 30px; margin-bottom: 10px">浪浪品種修改</h1>
    </div>
    <div style="text-align:right; margin-right:10px; text-decoration:none">
        <a asp-action="sbpetList" style="color:chocolate;" class="fa-solid fa-right-from-bracket"> 返回</a>
    </div>
    <hr />

    <div class="row" style="padding-bottom:90px; display:flex;justify-content:center;align-items:center">
        <div class="col-md-4">
            <form asp-action="Edit" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group" hidden>
                    <label asp-for="SubCategoryId" class="control-label"></label>
                    <input asp-for="SubCategoryId" class="form-control" />
                    <span asp-validation-for="SubCategoryId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <i class="fa-solid fa-paw">
                        <label asp-for="CategoryName" class="control-label"></label>
                    </i>
                    <input id="input" readonly asp-for="CategoryName" class="form-control" />
                    <span asp-validation-for="CategoryName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <i class="fa-solid fa-paw">
                        <label asp-for="SubCategoryName" class="control-label"></label>
                    </i>
                    <input id="input" asp-for="SubCategoryName" class="form-control" />
                    <span asp-validation-for="SubCategoryName" class="text-danger"></span>
                </div>
                <div class="form-group" hidden>
                    <label asp-for="CategoryId" class="control-label"></label>
                    <input asp-for="CategoryId" class="form-control" />
                    <span asp-validation-for="CategoryId" class="text-danger"></span>
                </div>
                <div class="form-group" style="text-align:right">
                    <i class="fa-solid fa-floppy-disk"><input type="submit" value="儲存" id="input" /></i>
                </div>
            </form>
        </div>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

qqqq/Views/BK_SubCategory/sbpetList.cshtml
@model IEnumerable<qqqq.ViewModels.CSubCategoryPet>

@{
    ViewData["Title"] = "List";
    Layout = "_BackLayout";

}
@section Styles{
    <style>
        #thead > tr > th {
            font-size: 18px;
            font-weight: 800;
            color: black;
        }

        #thead > tr {
            border: solid antiquewhite 2px;
            background-color: antiquewhite;
        }

        #tbody > tr {
            border: solid antiquewhite 2px;
            background-color: antiquewhite;
            font-size: 16px;
            font-weight: 600;
        }
    </style>
}
<h1 style="text-align:center; font-weight:900">浪浪類別管理</h1>
<div style="text-align:left; font-size:16px ; font-weight:600">
    @using (Html.BeginForm())
    {
        @:關鍵字 @Html.TextBox("txtKeyword", (object)@ViewBag.keyword, new { @style = "border-radius:30px;" })
        <button class="fa-solid fa-magnifying-glass" style=" border:none; background-color:transparent;"></button>

        <a asp-action="Create" class="fa-solid fa-user-plus" style="margin-top:8PX; float:right;font-size:20px;color:chocolate;"> 新增浪浪類別</a>
    }
</div>
<br />
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link href="~/css/BK_style.css" rel="stylesheet" />
</head>
<body>
    <div class="row ">
        <table class="table">
            <thead id="thead" style="text-align:center;">
                <tr style="font-size:20px">
                    <th>
                        @Html.DisplayNameFor(model => model.SubCategoryId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CategoryName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.SubCategoryName)
                    </th>
                    <th hidden>
                        @Html.DisplayNameFor(model => model.CategoryId)
                    </th>

                    <th colspan=3>
                        功能
                    </th>
                </tr>
            </thead>
            <tbody id="tbody" style="text-align:center;">
                @{ int Count = 0;
                    foreach (var item in Model)
                    {
                        Count++;
                        <tr>
                            <td>
                                @Count
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CategoryName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SubCategoryName)
                            </td>
                            <td hidden>
                                @Html.DisplayFor(modelItem => item.CategoryId)
                            </td>

                            <td>
                                @Html.ActionLink("", "Edit", "BK_SubCategory", new { id = item.SubCategoryId }, new { Class = "fa-solid fa-wrench", @style = "color:chocolate;font-size:16px" })
                            </td>
                            <td>
                                @Html.ActionLink("", "Delete", "BK_SubCategory", new { id = item.SubCategoryId }, new { Class = "fa-solid fa-trash-can", @style = "color:chocolate;font-size:16px", onclick = "return confirm('請確認是否要刪除?')" })
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</body>
</html>